# Generated by Django 3.0.2 on 2020-01-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
