# Generated by Django 3.0.2 on 2020-01-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200127_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publication_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
