# Generated by Django 3.0.2 on 2020-02-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip_address',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
