# Generated by Django 3.0.2 on 2020-02-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_review_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
