# Generated by Django 3.0.2 on 2020-02-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200213_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ip_address',
        ),
    ]
